# Generated by Django 4.1.3 on 2023-02-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cmdr',
            new_name='Db',
        ),
    ]
